import "./styles/all.css"
import "./styles/blog.css"
import "./styles/common.css"
import "./styles/contact.css"
import "./styles/index.css"
import "./styles/singleBlog.css"
import Header from "./components/header";
import Footer from "./components/footer";

// import type { Metadata } from "next";
// import localFont from "next/font/local";
import { ReactNode } from 'react';
//
// const geistSans = localFont({
//   src: "./fonts/GeistVF.woff",
//   variable: "--font-geist-sans",
//   weight: "100 200 300 400 500 600 700 800 900", // List of weights
// });
//
// const geistMono = localFont({
//   src: "./fonts/GeistMonoVF.woff",
//   variable: "--font-geist-mono",
//   weight: "100 200 300 400 500 600 700 800 900",
// });
//
// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// Define the prop types for the component
interface RootLayoutProps {
  children: ReactNode;
}

export default function RootLayout({children}:  RootLayoutProps) {
  return (
    <html lang="en">
      <body>
        <Header/>
          <main>{children}</main>
        <Footer />
      </body>
    </html>
  );
}
